### ISSUE TITLE
new action summary produces mistaken metadata

### ISSUE THREAD

**Issue by gilbahat** [datreeio/action-datree#16]
There are 2 issues with the github action summary:

1. excluded rules still appear as failed in the summary. this makes it really hard to tune what issues have been successfully excluded.
2. garbage metadata appears in rule failures. it seems like the first metadata name is picked up and replicated across the board, or something of that sorts. either way it is entirely incorrect and does not match source files.

**Comment by hadar-co** [comment]
Hi @gilbahat thanks for opening an issue, is the repo in which this happened public? An example of these issues will help us resolve them.

**Comment by gilbahat** [comment]
unfortunately it is not. I will try to see if I can get some examples from non-properietary components.

**Comment by gilbahat** [comment]
![Screen Shot 2022-10-12 at 18 01 04](https://user-images.githubusercontent.com/5927621/195378308-b3ba1eca-9a3f-4ab5-aae1-970b27c7300f.png)
![Screen Shot 2022-10-12 at 18 00 46](https://user-images.githubusercontent.com/5927621/195378311-f6c65f85-1db5-4f77-8e4f-29826e927fc4.png)

there we go. as you can see, the in-job run shows that cloudflared has been successfully excluded. however, it still looks like an error in the job summary.
you can also see that metadata refers to 'gatekeyper', a totally different component which is not present in the cloudflared yamls.

**Comment by hadar-co** [comment]
There was a bug where skipped files were not presented in the output, it is now fixed:)
