### ISSUE TITLE
Summary shows tests passed when schema validation failed

### ISSUE THREAD

**Issue by singhprincejeet** [datreeio/action-datree#18]
Summary of datree check shows the check to have passed when the schema validation failed. This makes it hard to understand the issue and creates confusion.

<img width="614" alt="image" src="https://user-images.githubusercontent.com/10202162/200645002-d1e12598-4617-40be-9317-6d181a13f72c.png">

**Comment by eyarz** [comment]
I think the confusing part is the last sentence - "all rules passed..."
@hadar-co maybe just replace it with something that will indicate there was a schema validation error?

**Comment by singhprincejeet** [comment]
> I think the confusing part is the last sentence - "all rules passed..."

Yes

**Comment by hadar-co** [comment]
@singhprincejeet good catch, it has been fixed :)
