### ISSUE TITLE
daTree IsKustomize

### ISSUE THREAD

**Issue by Plork** [datreeio/action-datree#2]
I see that in the readme you can enable isKustomization.
https://github.com/datreeio/action-datree#using-kustomize

however the action.yml lacks that input.
https://github.com/datreeio/action-datree/blob/main/action.yaml

Entrypoint does seem to be prepared.
https://github.com/datreeio/action-datree/blob/main/entrypoint.sh#L7

**Comment by hadar-co** [comment]
Fixed, thanks:)
