### ISSUE TITLE
library charts

### ISSUE THREAD

**Issue by loeken** [datreeio/action-datree#23]
hi i have a folder called charts with 2 folders inside a "common" library chart and another helm chart that uses the common library chart. With the github action it seems to error ( and fail ) on processing the library chart folder
```
*** Proceeding to test Helm chart: charts/common/Chart.yaml ***
Error: library charts are not installable
Error: plugin "datree" exited with error
```

is there an option to exclude the folder charts/common/* ? or the action to skip it if it detects a library chart?

**Comment by hadar-co** [comment]
Hi @loeken, it seems that you're running a test on a chart of type `library`. According to the [helm docs](https://helm.sh/docs/topics/library_charts/) library charts are not supposed to contain any templates. This is why you are getting this error.

Note that if you unzip one of your heimdall release zip files, and run a `helm datree test` against the unzipped chart, the test will run as expected.

**Comment by loeken** [comment]
hi,

i ve followed this article to setup my common library chart. based on this article:

"In the templates/ directory, any file that begins with an underscore(_) is not expected to output a Kubernetes manifest file. So by convention, helper templates and partials are placed in a _*.tpl or _*.yaml files." 

https://github.com/loeken/helm-charts/tree/main/charts/common/templates <- all my files are *.tpl files starting with an underscore

so from my point of view im following the helm docs and create a library chart, but the datree action doenst identify the type of this chart ( type = library ) and tries to run a check on the folder (which fails ), my question was if there was a way for me to use the existing datree action ( not manually unzip the files and run it ) to run a check in the structure that helm docs suggested

**Comment by loeken** [comment]
maybe something along the lines of:

```
  while read -r helmchart; do
    dir="$(dirname "$helmchart")"
    chart_type=`cat $helmchart|grep "type:"|cut -d' ' -f 2`
    if [ "$chart_type" != "library" ]; then
      echo "*** Proceeding to test Helm chart: $helmchart ***"

      process the chart here

    fi
  done < <(find "$PWD" -type f -name 'Chart.y*ml')
```

**Comment by hadar-co** [comment]
Ok, I think I see the issue:)
1. The action does not support testing multiple charts directly. You provided your root folder "charts" as the path to test, the action does not iterate over the charts, it seems like in your case it only tests the library chart. 
To support testing multiple charts, we created this script - [https://github.com/datreeio/helm-datree#testing-multiple-charts](https://github.com/datreeio/helm-datree#testing-multiple-charts)
2. Can you use the script and add your snippet above to ignore library charts and see that this resolves your issue?

**Comment by loeken** [comment]
thanks for the quick responses

looking at your script it does support testing multiple charts 
https://github.com/datreeio/action-datree/blob/main/entrypoint.sh#L154

this will search all files in the current folder matching Chart.y*ml and run a test for each Chart.yml found ( in line 147 )
```
helm datree test "$dir" $cliArguments -- $helmArgs
```

I've forked your repo and tested my changes ( and created a PR for you guys: https://github.com/datreeio/action-datree/pull/24 )

you can see the successfull execution here: https://github.com/loeken/helm-charts/actions/runs/3507915889/jobs/5875953077 

might make it easier for others too who want to test multiple charts ideally with your github action without having to build scripts around it

**Comment by hadar-co** [comment]
@loeken Awesome! Thanks for the PR🔥

**Comment by loeken** [comment]
cool then i guess my issue is solved :)

**Comment by loeken** [comment]
thanks again for the quick responses
