### ISSUE TITLE
action fails with kustomize with refs

### ISSUE THREAD

**Issue by Plork** [datreeio/action-datree#26]
When running the cli with the following:

```bash
  - name: Run Datree Policy Check
    uses: datreeio/action-datree@main
    with:
      path: kubernetes/application/overlay/test
      cliArguments: '--ignore-missing-schemas'
      isKustomization: true
```

This fails when the kustomize has a ref to a git repo.

`kubectl kustomize errored: error: accumulating resources: accumulation err='accumulating resources from 'ssh:: no such file or directory': no 'git' program on path: exec: "git": executable file not found in $PATH`

I saw that the datree/datreecli docker image does not have git installed:
https://github.com/datreeio/datree/blob/main/dockerfiles/image-datreeci/Dockerfile#L14

So easiest would be to add git to the container of the action:
https://github.com/datreeio/action-datree/blob/main/Dockerfile#L3

**Comment by hadar-co** [comment]
@Plork thanks for opening an issue:)
Can you share why you need `git` in your use-case?

**Comment by Plork** [comment]
I don't know what more I need to explain. When you have a Kustomize app and you are referencing a resource with a url instead of a path.

so in short running this:

datree kustomize test $inputpath $cliArguments -- $kustomizeArgs

and then the kustomization.yaml has:

```bash
resources:
  - git://github.com/repo/path/base
  ```
  
  instead of
```bash
resources:
  - ../base
  ```

**Comment by hadar-co** [comment]
I see. This is a specific use-case, I don't think we should add `git` to the image just for this, in most cases it is not needed.

You can do one of the following:
1. Add a step in your workflow that installs git before running datree.
OR
2. Check out the other git repo containing your desired resource and reference it with a path.

**Comment by Plork** [comment]
Oke ... but I do find it weird that it is functionality supported by the cli that won't work in the action. You support Kustomize via the cli .. but not all Kustomize?

I use this right before the datree action. 

```bash
        uses: actions/checkout@v2
```

So as you can see the github runner already has git.

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/4212271/205942813-584330cf-bee2-46f8-ad97-1ae5c80323a5.png">

The problem is that the container you use with the installed kubectl does not have git.
https://github.com/datreeio/datree/blob/main/dockerfiles/image-datreeci/Dockerfile#L10

This is not a specific use-case but common best practice to reference your bases via a repo. Otherwise all your overlays would change when you update your base. (not something you want with git-ops in a regulated environment.

**Comment by hadar-co** [comment]
@Plork We added git to the image, can you run again and let us know if it's resolved?

**Comment by Plork** [comment]
Awesome thnx will do asap 👍

**Comment by Plork** [comment]
you added it to the github action? Shouldnt you rebuilt the github action then for it to have affect.

**Comment by hadar-co** [comment]
There is nothing to build in the action itself, the action pulls the datreeci image on every run, and the image itself has been rebuilt
