### ISSUE TITLE
datree/datreeci:latest is not using latest CLI version - gets 'A new major CLI version is available, upgrade your CLI before the current version gets deprecated...'

### ISSUE THREAD

**Issue by HariSekhon** [datreeio/action-datree#4]
The docker image `datree/datreeci:latest` is not using the latest version of the CLI, so the action output is showing:

```
A new major CLI version is available, upgrade your CLI before the current version gets deprecated. Refer to our docs for version upgrade instructions - https://hub.datree.io/#a-1-install-the-datree-cli
```

I recommend this docker image is CI build whenever a new version tag is created on GitHub.

I tend to find the latest release of many github projects using the GitHub API endpoint: https://api.github.com/repos/datreeio/datree/releases/latest and taking the `tag_name` field, although it'd probably also work to just run `curl https://get.datree.io | /bin/bash` in the docker build every time there is a new tag.

**Comment by hadar-co** [comment]
Hey @HariSekhon, as you said the image was not updated correctly. It is now fixed.

Please let me know that this resolved the issue:)

**Comment by hadar-co** [comment]
@HariSekhon Hi, has this been resolved for you after the image update?

**Comment by HariSekhon** [comment]
Yes, thanks.
