### ISSUE TITLE
CRD Schema Location

### ISSUE THREAD

**Issue by bradkwadsworth-mw** [datreeio/action-datree#9]
Having an issue when adding a `cliArguments` parameter that contains a `--schema-location` with something like `{{ .ResourceKind }}_{{ .ResourceAPIVersion }}.json` in the schema location path. Not sure if there is an error going on with variable substitution or what.

**Comment by eyarz** [comment]
@bradkwadsworth-mw it may be an issue with action, datree CLI on just wrong setup.
To troubleshoot this quickly, can you please add a screenshot/copy of the error you're getting?
Also, to ensure you don't have an issue with the file name, can you write the full file path and name that you're targeting with the `schema-location` flag?

**Comment by bradkwadsworth-mw** [comment]
![Screen Shot 2022-07-18 at 12 18 10 PM](https://user-images.githubusercontent.com/79924581/179567174-db757719-f735-4d2d-8981-bb6474ac5604.png)

**Comment by hadar-co** [comment]
Hi @bradkwadsworth-mw , thanks for the info 👍🏽
I have managed to reproduce this, does indeed seem like the {{ . }} variables aren't expanded correctly. I'll update here when it's fixed:)

**Comment by bradkwadsworth-mw** [comment]
Awesome, thanks much!

**Comment by chr15murray** [comment]
I also hit this issue but managed to work around it by escaping the cli args and removing extra spaces. Note since I'm passing two args I have to escape the space between them too. 

For example:
```
cliArguments: "--schema-location=./.datree/schemas/dev/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json\ --policy-config=.datree/policies.yaml"
```

Will follow for a better fix though.

**Comment by hadar-co** [comment]
@chr15murray I realized that the {{.}} variables do not need spaces in order to work. So you can just pass your cliArguments like this:
```cliArguments: --schema-location ".datree/schemas/dev/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json" --policy-config .datree/policies.yaml```

This works for me, let me know if it works for you as well:)

**Comment by bradkwadsworth-mw** [comment]
When I removed the spaces I get ` k8s schema validation error: could not find schema` errors even though the schemas exists at that schema-location.

**Comment by bradkwadsworth-mw** [comment]
NVM, I think I got it working!

**Comment by hadar-co** [comment]
@bradkwadsworth-mw glad to hear 🤘 did you need to use some syntax hack or did it work by simply removing the spaces?

@chr15murray let me know if this works for you too:)

**Comment by bradkwadsworth-mw** [comment]
> I also hit this issue but managed to work around it by escaping the cli args and removing extra spaces. Note since I'm passing two args I have to escape the space between them too.
> 
> For example:
> 
> ```
> cliArguments: "--schema-location=./.datree/schemas/dev/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json\ --policy-config=.datree/policies.yaml"
> ```
> 
> Will follow for a better fix though.

This is what worked for me. Also removing ${{ github.workspace }} from the cliArgs helped as well.
